### ISSUE TITLE
Application class isn't usable out of Yabf

### ISSUE THREAD

**Issue by Mindsers** [Mindsers/yabf#16]
We recently externalize some common behaviors of applications inside an abstract class called `Application`. It's a great idea but it's not working.

Two cases:
- `createInstance` need to be implemented in `Application`. Having to implements it in each child cause duplication of code. Only the dependencies array may change sometimes. Also it is impossible to really implement it because `InjectorService` is not exposed outside of **Yabf**.
- It impossible to inherit from `Application` because it needs `InjectorService` as first argument. So, even if we don't use the `createInstance` method we can't use `Application` as mother class.

## Solutions

For the first case, we may use the [Template Pattern](https://en.wikipedia.org/wiki/Template_method_pattern) as proposed in #15. We could encapsulate all the logic around `InjectorService` and ask children for dependency list.

For the second case, we may use an interface instead of a class. If we do that we allow people to use other DI services if they respect the interface.

**Comment by Mindsers** [comment]
@izardj @PaulVenet I need outside perspectives about this issue... Mostly for the first case (the second is done)

You may want more informations: 
- [Application's children should implements `createInstance` method](https://github.com/Mindsers/yabf/blob/develop/docs/application-should-have-createinstance-method.md)
- [Application API](https://github.com/Mindsers/yabf/blob/develop/docs/api/application.md)

**Comment by PaulVenet** [comment]
hum, i Don't know dude. I never do this and i Don't see how to do this ..

________________________________
De : Nathanael CHERRIER <notifications@github.com>
Envoyé : jeudi 13 septembre 2018 11:30:17
À : Mindsers/yabf
Cc : PaulVenet; Mention
Objet : Re: [Mindsers/yabf] Application class isn't usable out of Yabf (#16)


@PaulVenet<https://github.com/PaulVenet> So, the real problem is that in typescript it isn't possible to define an abstract static method. Do you see another solution to enforce implementation of a static method in children of an abstract class?

**Comment by Mindsers** [comment]
@PaulVenet Problem soved in #18. If anyone have a better solution, I'll merge it soon ;)
